src/historie/urls.py
from django.urls import path
from . import views

app_name = 'historie'  # here for namespacing of urls.

urlpatterns = [
    path("", views.list, name="list"),
    path('ajax/fetch_entries', views.fetch_entries, name="fetch_entries")
]

src/login/urls.py
from django.urls import path
from . import views


app_name = 'login'  # here for namespacing of urls.

urlpatterns = [
    path("", views.main_screen, name="homepage"),
    path('logout/', views.logout_request, name="logout")
]

src/historie/models.py
from django.contrib.auth.models import User
from simple_history import register

register(User)

src/historie/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.core.paginator import Paginator

from mitglieder.models import Mitglied, MitgliedMail, MitgliedAmt
from aemter.models import Organisationseinheit, Unterbereich, Funktion, Recht, FunktionRecht
from checklisten.models import Checkliste, ChecklisteAufgabe, ChecklisteRecht
from django.contrib.auth.models import User
from django.db.models import Q

def list(request):
    """
    Diese View wird aufgerufen, wenn der Nutzer über einen Link erstmalig die Historie aufruft (z.B. aus dem Menü heraus).
    
    Folgende Aufgaben werden von dieser übernommen:

    * Bereitstellung von Daten: Es werden alle Historien-Einträge für alle Tabs geholt, anschließend in Seiten je 15 Elemente aufgeteilt und jeweils die erste Seite an die View übergeben.
    * Zugriffsbeschränkung: Zugriff wird nur gewährt, wenn der Nutzer angemeldet UND Administrator ist.
    * Rendern des Templates der gesamten Seite.

    :param request: Die HTML-Request, welche den Aufruf der View ausgelöst hat.
    :return: Die gerenderte View.
    """
    # Access restrictions
    if not request.user.is_authenticated:
        messages.error(request, "Du musst angemeldet sein, um diese Seite sehen zu können.")
        return redirect("/")
    if not request.user.is_superuser:
        messages.error(request, "Du musst Admin sein, um diese Seite aufrufen zu können.")
        return redirect("/mitglieder")

    # Fetch all entries
    mitglieder = Mitglied.history.all()
    mitgliederMails = MitgliedMail.history.all()
    mitgliederAemter = MitgliedAmt.history.all()

    referate = Organisationseinheit.history.all()
    unterbereiche = Unterbereich.history.all()
    aemter = Funktion.history.all()
    rechte = Recht.history.all()
    aemterRechte = FunktionRecht.history.all()

    checklisten = Checkliste.history.all()
    checklistenRechte = ChecklisteRecht.history.all()
    checklistenAufgaben = ChecklisteAufgabe.history.all()

    users = User.history.all()

    # Paginate results
    page_number = 1

    mitgliederPaginator = Paginator(mitglieder, 15)
    mitgliederMailsPaginator = Paginator(mitgliederMails, 15)
    mitgliederAemterPaginator = Paginator(mitgliederAemter, 15)

    referatePaginator = Paginator(referate, 15)
    unterbereichePaginator = Paginator(unterbereiche, 15)
    aemterPaginator = Paginator(aemter, 15)
    rechtePaginator = Paginator(rechte, 15)
    aemterRechtePaginator = Paginator(aemterRechte, 15)

    checklistenPaginator = Paginator(checklisten, 15)
    checklistenRechtePaginator = Paginator(checklistenRechte, 15)
    checklistenAufgabenPaginator = Paginator(checklistenAufgaben, 15)

    usersPaginator = Paginator(users, 15)

    # Get first page for each tab
    mitgliederPage = mitgliederPaginator.get_page(page_number)
    mitgliederMailsPage = mitgliederMailsPaginator.get_page(page_number)
    mitgliederAemterPage = mitgliederAemterPaginator.get_page(page_number)

    referatePage = referatePaginator.get_page(page_number)
    unterbereichePage = unterbereichePaginator.get_page(page_number)
    aemterPage = aemterPaginator.get_page(page_number)
    rechtePage = rechtePaginator.get_page(page_number)
    aemterRechtePage = aemterRechtePaginator.get_page(page_number)

    checklistenPage = checklistenPaginator.get_page(page_number)
    checklistenRechtePage = checklistenRechtePaginator.get_page(page_number)
    checklistenAufgabenPage = checklistenAufgabenPaginator.get_page(page_number)

    usersPage = usersPaginator.get_page(page_number)

    return render(request=request,
                  template_name="historie/list.html",
                  context={"mitglieder": mitgliederPage,
                           "mitgliederMails": mitgliederMailsPage,
                           "mitgliederAemter": mitgliederAemterPage,
                           "referate": referatePage,
                           "unterbereiche": unterbereichePage,
                           "aemter": aemterPage,
                           "rechte": rechtePage,
                           "aemterRechte": aemterRechtePage,
                           "checklisten": checklistenPage,
                           "checklistenRechte": checklistenRechtePage,
                           "checklistenAufgaben": checklistenAufgabenPage,
                           "users": usersPage})

def fetch_entries(request):
    """
    Mit dieser View kann eine Liste von Historien-Einträgen mitsamt passender Pagination angefordert werden, welche die Einträge enthält, die...

    * ...zum angegeben Tab bzw. Model gehören.
    * ...in denen die angegebenen Suchbegriffe vorkommen.
    * ...zur angeforderten Seite gehören.

    Folgende Aufgaben werden durch diese übernommen:

    * Zugriffsbeschränkung: Zugriff wird nur gewährt, wenn der Nutzer angemeldet UND Administrator ist.
    * Bereitstellung von Daten: Die View stellt die gewünschte Seite der Historien-Einträge bereit, welche für das gewünschte Model zu den angegebenen Suchbegriffen gefunden wurden.
    * Rendern der Liste mit den passenden Historien-Einträgen und der zugehörigen Pagination.

    Je nachdem, ob in der `request` Suchbegriffe mitgegeben wurden, werden entweder alle Einträge oder die nach den Suchbegriffen
    gefilterten Einträge bereitgestellt. Die Filterung funktioniert dabei folgendermaßen:
    
    * Das gewünschte Model wird dahingehend untersucht, ob die wichtigsten Felder eines Eintrags (bei Mitgliedern z.B. ID, Vorname und Name) die Suchbegriffe enthalten.
    * Hierfür werden die in Django integrierten `Q Objects` verwendet.
    * Alle gefundenen Einträge werden in einem QuerySet zusammengefasst, welches anschließend an ``render`` übergeben wird.

    :param request: Die HTML-Request, welche den Aufruf der View ausgelöst hat. 
        Enthält stets die gewünschte Seitenzahl, den Namen des Tabs und damit Models, zu dem das Ergebnis geliefert werden soll und optional Suchbegriffe, nach denen das Model durchsucht werden soll.
    :return: Die gerenderte Liste mit den entsprechenden Historien-Einträgen und der zugehörigen Pagination.
    """
    # Access restrictions
    if not request.user.is_authenticated:
        return HttpResponse("Permission denied")
    if not request.user.is_superuser:
        return HttpResponse("Permission denied")
    
    # Get data from request
    searchterm = request.GET.get('search')
    page_number = request.GET.get('page')
    selected_tab = request.GET.get('tab')

    # Get indvidiual search terms
    searchterms = None
    if searchterm:
        searchterms = searchterm.split(' ')
        for term in searchterms:
            term = term.strip()
    
    if not searchterm:
        searchterms = [""]
    
    # Get data for selected tab and search terms
    data = None
    if selected_tab == "Mitglied":
        data = Mitglied.history.none()
        for term in searchterms:
            data = data | Mitglied.history.filter(Q(id__icontains=term) | Q(vorname__icontains=term) | Q(name__icontains=term))
    if selected_tab == "MitgliedMail":
        data = MitgliedMail.history.none()
        for term in searchterms:
            data =  data | MitgliedMail.history.filter(Q(mitglied__id__icontains=term) | Q(mitglied__vorname__icontains=term) | Q(mitglied__name__icontains=term) | Q(email__icontains=term))
    if selected_tab == "MitgliedAmt":
        data = MitgliedAmt.history.none()
        for term in searchterms:
            data = data | MitgliedAmt.history.filter(Q(mitglied__id__icontains=term) | Q(mitglied__vorname__icontains=term) | Q(mitglied__name__icontains=term) 
                | Q(funktion__id__icontains=term) | Q(funktion__bezeichnung__icontains=term) 
                | Q(funktion__organisationseinheit__bezeichnung__icontains=term)
                | Q(funktion__unterbereich__bezeichnung__icontains=term))

  
    if selected_tab == "Organisationseinheit":
        data = Organisationseinheit.history.none()
        for term in searchterms:
            data = data | Organisationseinheit.history.filter(Q(id__icontains=term) | Q(bezeichnung__icontains=term))
    if selected_tab == "Unterbereich":
        data = Unterbereich.history.none()
        for term in searchterms:
            data = data | Unterbereich.history.filter(Q(id__icontains=term) | Q(bezeichnung__icontains=term) | Q(organisationseinheit__id__icontains=term) | Q(organisationseinheit__bezeichnung__icontains=term))
    if selected_tab == "Amt":
        data = Funktion.history.none()
        for term in searchterms:
            data = data | Funktion.history.filter(Q(id__icontains=term) | Q(bezeichnung__icontains=term)
                | Q(organisationseinheit__id__icontains=term) | Q(organisationseinheit__bezeichnung__icontains=term)
                | Q(unterbereich__id__icontains=term) | Q(unterbereich__bezeichnung__icontains=term))
    if selected_tab == "Recht":
        data = Recht.history.none()
        for term in searchterms:
            data = data | Recht.history.filter(Q(id__icontains=term) | Q(bezeichnung__icontains=term))
    if selected_tab == "AmtRecht":
        data = FunktionRecht.history.none()
        for term in searchterms:
            data = data | FunktionRecht.history.filter(Q(funktion__id__icontains=term) | Q(funktion__bezeichnung__icontains=term)
                | Q(funktion__organisationseinheit__bezeichnung__icontains=term)
                | Q(funktion__unterbereich__bezeichnung__icontains=term)
                | Q(recht__id__icontains=term) | Q(recht__bezeichnung__icontains=term))
    
    if selected_tab == "Checkliste":
        data = Checkliste.history.none()
        for term in searchterms:
            data = data | Checkliste.history.filter(Q(id__icontains=term) 
                | Q(mitglied__id__icontains=term) | Q(mitglied__vorname__icontains=term) | Q(mitglied__name__icontains=term) 

src/historie/templates/historie/_modalDataIncludes.html
{% load t_historie.to_class_name %}

{% if entry|to_class_name == "HistoricalMitglied" %}
{% include 'historie/modalData/mitgliedModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalMitgliedMail" %}
{% include 'historie/modalData/mitgliedMailModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalMitgliedAmt" %}
{% include 'historie/modalData/mitgliedAmtModalData.html' %}
{% endif %}

{% if entry|to_class_name == "HistoricalKandidatur" %}
{% include 'historie/modalData/kandidaturModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalKandidaturMail" %}
{% include 'historie/modalData/kandidaturMailModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalKandidaturAmt" %}
{% include 'historie/modalData/kandidaturAmtModalData.html' %}
{% endif %}

{% if entry|to_class_name == "HistoricalOrganisationseinheit" %}
{% include 'historie/modalData/referatModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalUnterbereich" %}
{% include 'historie/modalData/unterbereichModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalFunktion" %}
{% include 'historie/modalData/amtModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalRecht" %}
{% include 'historie/modalData/rechtModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalFunktionRecht" %}
{% include 'historie/modalData/amtRechtModalData.html' %}
{% endif %}

{% if entry|to_class_name == "HistoricalCheckliste" %}
{% include 'historie/modalData/checklisteModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalChecklisteAufgabe" %}
{% include 'historie/modalData/checklisteAufgabeModalData.html' %}
{% endif %}
{% if entry|to_class_name == "HistoricalChecklisteRecht" %}
{% include 'historie/modalData/checklisteRechtModalData.html' %}
{% endif %}

{% if entry|to_class_name == "HistoricalUser" %}
{% include 'historie/modalData/userModalData.html' %}
{% endif %}

src/historie/templates/historie/_noResultsRow.html
<li class="collection-item">
    <a class="secondary-content"><i class="material-icons">mood_bad</i></a>
    Es wurden keine Einträge gefunden, die den Suchbegriffen entsprechen.
</li>

src/historie/templates/historie/_titleBuilder.html
{% load t_historie.to_class_name %}

{% if entry|to_class_name == "HistoricalMitglied" %}
Mitglied {{entry.id}} ({{entry.vorname}} {{entry.name}})
{% endif %}
{% if entry|to_class_name == "HistoricalMitgliedMail" %}
E-Mail-Adresse zu Mitglied {{entry.mitglied_id}} ({{latestMitglied.vorname}} {{latestMitglied.name}})
{% endif %}
{% if entry|to_class_name == "HistoricalMitgliedAmt" %}
Zuordnung von Funktion {{entry.funktion_id}} ({{latestAmt.bezeichnung}}
{% if latestUnterbereich.bezeichnung %}{{latestUnterbereich.bezeichnung}} {% endif %}
{{latestReferat.bezeichnung}})
zu Mitglied {{entry.mitglied_id}} ({{latestMitglied.vorname}} {{latestMitglied.name}})
{% endif %}

{% if entry|to_class_name == "HistoricalKandidatur" %}
Kandidatur {{entry.id}} ({{entry.vorname}} {{entry.name}})
{% endif %}
{% if entry|to_class_name == "HistoricalKandidaturMail" %}
E-Mail-Adresse zu Kandidatur {{entry.kandidatur_id}} ({{latestKandidatur.vorname}} {{latestKandidatur.name}})
{% endif %}
{% if entry|to_class_name == "HistoricalKandidaturAmt" %}
Zuordnung von Funktion {{entry.funktion_id}} ({{latestAmt.bezeichnung}}
{% if latestUnterbereich.bezeichnung %}{{latestUnterbereich.bezeichnung}} {% endif %}
{{latestReferat.bezeichnung}})
zu Kandidatur {{entry.kandidatur_id}} ({{latestKandidatur.vorname}} {{latestKandidatur.name}})
{% endif %}

{% if entry|to_class_name == "HistoricalOrganisationseinheit" %}
Organisationseinheit {{entry.id}} ({{entry.bezeichnung}})
{% endif %}
{% if entry|to_class_name == "HistoricalUnterbereich" %}
Unterbereich {{entry.id}} ({{entry.bezeichnung}}) zu Organisationseinheit {{entry.organisationseinheit_id}} ({{latestReferat.bezeichnung}})
{% endif %}
{% if entry|to_class_name == "HistoricalFunktion" %}
Funktion {{entry.id}} ({{entry.bezeichnung}}) in Organisationseinheit
{{entry.organisationseinheit_id}} ({{latestReferat.bezeichnung}}){% if entry.unterbereich_id %}, Unterbereich
{{entry.unterbereich_id}} ({{latestUnterbereich.bezeichnung}}){% endif %}
{% endif %}
{% if entry|to_class_name == "HistoricalRecht" %}
Recht {{entry.id}} ({{entry.bezeichnung}})
{% endif %}
{% if entry|to_class_name == "HistoricalFunktionRecht" %}
Recht {{entry.recht_id}} ({{latestRecht.bezeichnung}}) zu Funktion {{entry.funktion_id}} ({{latestAmt.bezeichnung}}
{% if latestUnterbereich %}{{latestUnterbereich.bezeichnung}} {% endif %}{{latestReferat.bezeichnung}})
{% endif %}

{% if entry|to_class_name == "HistoricalCheckliste" %}
Checkliste {{entry.id}} ({{latestMitglied.vorname}} {{latestMitglied.name}}{% if entry.amt_id %} - {{latestOrganisationseinheit.bezeichnung}} {% if latestUnterbereich %}{{latestUnterbereich.bezeichnung}} {% endif %}{{latestFunktion.bezeichnung}}{% endif %})
{% endif %}
{% if entry|to_class_name == "HistoricalChecklisteAufgabe" %}
Aufgabe {{entry.aufgabe_id}} ({{latestAufgabe.bezeichnung}}) auf Checkliste {{entry.checkliste_id}} ({{latestMitglied.vorname}} {{latestMitglied.name}}{% if latestCheckliste.amt_id %} - {{latestOrganisationseinheit.bezeichnung}} {% if latestUnterbereich %}{{latestUnterbereich.bezeichnung}} {% endif %}{{latestFunktion.bezeichnung}}{% endif %})
{% endif %}
{% if entry|to_class_name == "HistoricalChecklisteRecht" %}
Recht {{entry.recht_id}} ({{latestRecht.bezeichnung}}) auf Checkliste {{entry.checkliste_id}} ({{latestMitglied.vorname}} {{latestMitglied.name}}{% if latestCheckliste.amt_id %} - {{latestOrganisationseinheit.bezeichnung}} {% if latestUnterbereich %}{{latestUnterbereich.bezeichnung}} {% endif %}{{latestFunktion.bezeichnung}}{% endif %})
{% endif %}

{% if entry|to_class_name == "HistoricalUser" %}
Nutzer {{entry.id}} ({{entry.username}})
{% endif %}

{% if entry.history_type == "+" %}hinzugefügt{% endif %}
{% if entry.history_type == "~" %}geändert{% endif %}
{% if entry.history_type == "-" %}gelöscht{% endif %}

src/historie/templates/historie/list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s12 m12 l6">
    <h3>Historie</h3>
    <span id="selectedTab" style="display: none;">Mitglied</span>
  </div>

  <div class="col s12">
    {% csrf_token %}
    <div class="input-field inline" style="margin-top: 27px">
      <input class="validate" type="search" name="search" id="search" data-url="{% url 'historie:fetch_entries' %}">
      <label for="search">Suchen...</label>
    </div>
    <a class="btn-floating waves-effect waves-light amber" id="searchButton">
      <i class="material-icons black-text">search</i>
    </a>
  </div>

<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s2"><a class="tab-link active" data-tab="Mitglied" id="MitgliedTab" href="#mitgliederTab">Mitglieder</a></li>
      <li class="tab col s2"><a class="tab-link" data-tab="Kandidatur" id="KandidaturenTab" href="#kandidaturenTab">Kandidaturen</a></li>
      <li class="tab col s2"><a class="tab-link" data-tab="Organisationseinheit" id="AmtTab" href="#aemterTab">Funktionen</a></li>
      <li class="tab col s2"><a class="tab-link" data-tab="Checkliste" id="ChecklisteTab" href="#checklistenTab">Checklisten</a></li>
      <li class="tab col s3"><a class="tab-link" data-tab="User" href="#nutzerTab">Systemnutzer</a></li>
    </ul>
  </div>
  {% include 'historie/tabs/mitgliederTab.html' %}
  {% include 'historie/tabs/kandidaturenTab.html' %}
  {% include 'historie/tabs/aemterTab.html' %}
  <!-- For some reason Django couldn't find the template, so the code for the Checklisten tab lives here now -->
  <div id="checklistenTab" class="col s12">
    <ul class="tabs secondary-tabs">
        <li class="tab col s4"><a class="tab-link active" data-tab="Checkliste" href="#checklistenTab2">Checklisten</a></li>
        <li class="tab col s4"><a class="tab-link" data-tab="ChecklisteAufgabe" href="#checklistenAufgabenTab">Aufgaben</a></li>
        <li class="tab col s4"><a class="tab-link" data-tab="ChecklisteRecht" href="#checklistenRechteTab">Rechte</a></li>
    </ul>
    <div id="checklistenTab2">
        {% include 'historie/row.html' with data=checklisten %}
    </div>
    <div id ="checklistenAufgabenTab">
        {% include 'historie/row.html' with data=checklistenAufgaben %}
    </div>
    <div id="checklistenRechteTab">
        {% include 'historie/row.html' with data=checklistenRechte %}
    </div>
  </div>
  {% include 'historie/tabs/nutzerTab.html' %}  
</div>

<script>
  var page = 1;

  $(document).ready(function() {
    // Initialize tabs
    var el = document.querySelectorAll('.tabs');
    var options;
    var instance = M.Tabs.init(el, options);

    // Initialize modals
    var elems = document.querySelectorAll('.modal');
    var options;
    var instances = M.Modal.init(elems, options);


    // Register event handlers
    $(".tab-link").on("click", function(event) {
      var selectedTab = $(event.target).attr("data-tab");

      // Update target on top tabs accordingly
      if(selectedTab == "Mitglied" || selectedTab == "MitgliedMail" || selectedTab == "MitgliedAmt")
        $("#MitgliedTab").attr("data-tab", selectedTab);
      if(selectedTab == "Organisationseinheit" || selectedTab == "Unterbereich" || selectedTab == "Amt" || selectedTab == "Recht" || selectedTab == "AmtRecht")
        $("#AmtTab").attr("data-tab", selectedTab);

      // Reset search before switching tabs to avoid confusion
      $("#search").val("");
      $("label[for='search']").removeClass("active");
      page = 1;

      $("#selectedTab").text(selectedTab);
      fetchEntries();
    });

    $(".page-link").on("click", function(event) {
      page = $(event.target).attr("data-page");
      fetchEntries();
    });

    $("#searchButton").on("click", function(event) {
      page = 1;
      fetchEntries();
    });

    function fetchEntries() {
      var search = $("#search").val();
      var url = $("#search").attr("data-url");
      var tab = $("#selectedTab").text();

      $.ajax({
        type: 'GET',
        url: url,
        data: {
          search: search,
          page: page,
          tab: tab
        },
        success: function(data) {
          // Update displayed data
          switch(tab) {
            case "Mitglied":
              $("#mitgliederStammdatenTab").html(data);
              break;
            case "MitgliedMail":
              $("#mitgliederMailsTab").html(data);
              break;
            case "MitgliedAmt":
              $("#mitgliederAemterTab").html(data);
              break;
            case "Kandidatur":
              $("#kandidaturenStammdatenTab").html(data);
              break;
            case "KandidaturMail":
              $("#kandidaturenMailsTab").html(data);
              break;
            case "KandidaturAmt":
              $("#kandidaturenAemterTab").html(data);
              break;
            case "Organisationseinheit":
              $("#referateTab").html(data);
              break;
            case "Unterbereich":
              $("#unterbereicheTab").html(data);
              break;
            case "Amt":
              $("#aemterTab2").html(data);
              break;
            case "Recht":
              $("#rechteTab").html(data);
              break;
            case "AmtRecht":
              $("#aemterRechteTab").html(data);
              break;
            case "User":
              $("#nutzerTab").html(data);
              break;
            case "Checkliste":
              $("#checklistenTab2").html(data);
              break;
            case "ChecklisteAufgabe":
              $("#checklistenAufgabenTab").html(data);
              break;
            case "ChecklisteRecht":
              $("#checklistenRechteTab").html(data);
              break;
          }

          // Unbind old listeners to prevent multi-firing of events
          $(".page-link").off("click");

          // Re-add event listener
          $(".page-link").on("click", function(event) {
            page = $(event.target).attr("data-page");
            fetchEntries();
          });

          // Re-initialize modals
          var elems = document.querySelectorAll('.modal');
          var options;
          var instances = M.Modal.init(elems, options);
        }
      });
    }
  });
</script>

{% endblock %}

src/historie/templates/historie/rowContent.html
{% load t_historie.to_class_name %}

<div id="modal{{entry|to_class_name}}{{entry.history_id}}" class="modal">
  <div class="modal-content">
    <h4>
      {% include 'historie/_titleBuilder.html' %}
    </h4>
    <div>
      <br />
      <p><b>Zeitpunkt: </b> {{ entry.history_date|date:'d.m.Y H:i' }}</p>
      <p><b>Nutzer: </b> {{ entry.history_user }}</p>
      <br />
      <h5>
        {% if entry.history_type == "+" %}Hinzugefügter{% endif %}
        {% if entry.history_type == "-" %}Gelöschter{% endif %}
        {% if entry.history_type == "~" %}Neuer{% endif %}
        Datensatz
      </h5>
      {% include 'historie/_modalDataIncludes.html' %}
    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-close waves-effect btn-flat">Schliessen</a>
  </div>
</div>

<li class="collection-item historie-collection-item modal-trigger" href="#modal{{entry|to_class_name}}{{entry.history_id}}">
  <a class="secondary-content">
    <i class="material-icons">
      {% if entry.history_type == "+" %}add{% endif %}
      {% if entry.history_type == "~" %}edit{% endif %}
      {% if entry.history_type == "-" %}delete{% endif %}
    </i>
  </a>
  {{ entry.history_date|date:'d.m.Y H:i' }} –
  {% include 'historie/_titleBuilder.html' %}
</li>