src/aemter/urls.py
from django.urls import path
from . import views
#from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static


app_name = 'aemter'  # here for namespacing of urls.

urlpatterns = [
    path("", views.main_screen, name="homepage"), 
] 

src/login/urls.py
from django.urls import path
from . import views


app_name = 'login'  # here for namespacing of urls.

urlpatterns = [
    path("", views.main_screen, name="homepage"),
    path('logout/', views.logout_request, name="logout")
]

src/mitglieder/urls.py
from django.urls import path
from . import views

app_name = 'mitglieder'  # here for namespacing of urls.

urlpatterns = [
    path("", views.main_screen, name="homepage"),
    path("erstellen", views.mitgliedErstellenView, name="erstellenView"),
    path("erstellen/speichern", views.erstellen, name="erstellen"),
    path("<int:mitglied_id>/bearbeiten", views.mitgliedBearbeitenView, name="bearbeitenView"),
    path("<int:mitglied_id>/bearbeiten/speichern", views.speichern, name="speichern"),

    path('ajax/laden', views.mitglied_laden, name='mitglied_laden'),
    path("ajax/mitglieder-loeschen", views.mitglieder_loeschen, name="mitglieder_loeschen"),
    path('ajax/bereiche-laden', views.bereiche_laden, name='bereiche_laden'),
    path('ajax/funktionen-laden', views.funktionen_laden, name='aemter_laden'),
    path('ajax/funktionen-html-laden', views.funktionen_html_laden, name='aemter_html_laden'),
    path('ajax/<int:mitglied_id>/funktionen-max-member-ueberpruefen', views.funktionen_max_member_ueberpruefen, name='funktionen-max-member-ueberpruefen'),
    path('ajax/funktion-loeschen', views.funktion_loeschen, name='amt_loeschen'),
    path('ajax/email-html-laden', views.email_html_laden, name='email_html_laden'),
    path('ajax/email-loeschen', views.email_loeschen, name='email_loeschen'),
    path('ajax/suchen', views.suchen, name="suchen"),
]

src/aemter/models.py
from django.db import models
from simple_history.models import HistoricalRecords

class Organisationseinheit(models.Model):
    """
        Datenbankmodell Organisationseinheit

        Felder:

        * bezeichnung
        * history
        * funktionen_ohne_unterbereich_count
    """
    bezeichnung = models.CharField(max_length=50, null=False)
    history = HistoricalRecords()
    funktionen_ohne_unterbereich_count = models.IntegerField(default=0)

    def __str__(self):
        return self.bezeichnung
    def __unicode__(self):
        return u'%s' % self.bezeichnung
    class Meta:
        verbose_name = "Organisationseinheit"
        verbose_name_plural = "Organisationseinheiten"

class Unterbereich(models.Model):
    """
        Datenbankmodell Unterbereich

        Felder:

        * bezeichnung
        * organisationseinheit (Referenziert zugehörige Organisationseinheit)
        * history
    """
    bezeichnung = models.CharField(max_length=50, null=False)
    organisationseinheit = models.ForeignKey(Organisationseinheit, on_delete=models.CASCADE, null=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.bezeichnung + " (" + self.organisationseinheit.__str__() + ")"
    def __unicode__(self):
        return u'%s' % self.bezeichnung
    class Meta:
        verbose_name = "Unterbereich"
        verbose_name_plural = "Unterbereiche"

class Funktion(models.Model):
    """
        Datenbankmodell Funktion

        Felder:

        * bezeichnung
        * workload
        * max_members (Maximale Anzahl an Mitgliedern in der Funktion)
        * organisationseinheit (Referenziert zugehörige Organisationseinheit)
        * unterbereich (Referenziert zugehörigen Unterbereich)
            Unterbereich kann null sein
        * history
    """
    bezeichnung = models.CharField(max_length=50, null=False)
    workload = models.IntegerField(null=True)
    max_members = models.IntegerField(null=False)
    organisationseinheit = models.ForeignKey(Organisationseinheit, on_delete=models.CASCADE, null=True, blank=True)
    unterbereich = models.ForeignKey(Unterbereich, on_delete=models.CASCADE, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        if self.unterbereich is None:
            return self.bezeichnung + " (" + self.organisationseinheit.__str__() + ")"
        else:
            return self.bezeichnung + ' ' + self.unterbereich.__str__()
    def tostring(self):
        return self.__str__()
    class Meta:
        verbose_name = "Funktion"
        verbose_name_plural = "Funktionen"

class Recht(models.Model):
    """
        Datenbankmodell Recht

        Felder:

        * bezeichnung
        * history
    """
    bezeichnung = models.CharField(max_length=50, null=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.bezeichnung
    class Meta:
        verbose_name = "Recht"
        verbose_name_plural = "Rechte"

class FunktionRecht(models.Model):
    """
        Datenbankmodell FunktionRecht

        Felder:

        * funktion (Referenziert zugehörige Funktion)
        * recht (Referenziert zugehöriges Recht)
        * history
    """
    funktion = models.ForeignKey(Funktion, on_delete=models.CASCADE, null=False)
    recht = models.ForeignKey(Recht, on_delete=models.CASCADE, null=False)
    history = HistoricalRecords()
    def __str__(self):
        return self.funktion.__str__() + ": " + self.recht.__str__()
    class Meta:
        verbose_name = "Zuordnung Funktion-Recht"
        verbose_name_plural = "Zuordnungen Funktion-Recht"

src/mitglieder/models.py
from datetime import date
from django.db import models
from django.db.models import Q
from simple_history.models import HistoricalRecords
from aemter.models import Funktion

class Mitglied(models.Model):
    """
    Datenbankmodell Mitglied

    Felder:

    * name: Nachname des Mitglieds. Darf nicht null sein.
    * vorname: Vorname des Mitglieds. Darf nicht null sein.
    * spitzname: Spitzname des Mitglieds. Kann null sein.
    * tel_mobil: Telefonnummer des Mitglieds. Kann null sein.

    * tel_weitergabe: Stellt dar, ob die Telefonnummer des Mitglieds im Notfall weitergegeben werden darf. Standard ist False.
    * wahl_angenommen: Stellt dar, ob das Mitglied die Wahl bereits angenommen hat. Standard ist False.
    * kenntnis_ordn: Stellt dar, ob das Mitglied die Kenntnis der Ordnungen bereits eingereicht hat. Standard ist False.
    * verpfl_datengeheimnis: Stellt dar, ob das Mitglied die Verpflichtung zum Datengeheimnis bereits akzeptiert hat. Standard ist False.
    * stammdatenblatt: Stellt dar, ob das Mitglied das Stammdatenblatt bereits eingereicht hat. Standard ist False.
    * history
    """
    name = models.CharField(max_length=50, null=False)
    vorname = models.CharField(max_length=50, null=False)
    spitzname = models.CharField(max_length=50, null=True)
    tel_mobil = models.CharField(max_length=15, null=True)
    tel_weitergabe = models.BooleanField(default=False, null=False)

    auto_checkliste = models.BooleanField(default=True, null=False)
    wahl_angenommen = models.BooleanField(default=False, null=False)
    kenntnis_ordn = models.BooleanField(default=False, null=False)
    verpfl_datengeheimnis = models.BooleanField(default=False, null=False)
    stammdatenblatt = models.BooleanField(default=False, null=False)

    history = HistoricalRecords()

    def __str__(self):
        return self.vorname + " " + self.name

    def curr_funktion_count(self):
        """
        Funktion, die die Anzahl der derzeitigen Funktionen des Mitglieds zurückgibt.
        """
        return self.mitgliedamt_set\
            .filter(Q(amtszeit_ende__isnull=True) | Q(amtszeit_ende__gte=date.today()))\
            .count()

    def curr_funktion_first(self):
        """
        Funktion, die die erste Funktion des Mitglieds zurückgibt
        oder None wenn das Mitglied keine Funktion innehat.
        """
        if self.mitgliedamt_set\
                .filter(Q(amtszeit_ende__isnull=True) | Q(amtszeit_ende__gte=date.today())):
            return self.mitgliedamt_set\
                .filter(Q(amtszeit_ende__isnull=True) | Q(amtszeit_ende__gte=date.today()))\
                .first()\
                .funktion
        else:
            return None

    def admission_data_complete(self):
        """
        Funktion, die prüft, ob alle Daten für die Aufnahme als Mitglied vorhanden sind.
        """
        if self.wahl_angenommen and self.kenntnis_ordn and self.verpfl_datengeheimnis and self.stammdatenblatt:
            return True
        else:
            return False

    class Meta:
        verbose_name = "Mitglied"
        verbose_name_plural = "Mitglieder"


class MitgliedAmt(models.Model):
    """
    Datenbankmodell Zuordnung Mitglied-Amt

    Felder:

    * mitglied: Referenziert eine Mitglied. Darf nicht null sein.
    * funktion: Referenziert eine Funktion. Darf nicht null sein.
    * amtszeit_beginn: Datum des Beginns der Amtszeit. Kann null sein.
    * amtszeit_ende: Datum des Endes der Amtszeit. Kann null sein.
    * history

    Es ist zu beachten, dass diese Zuordnung gelöscht wird, wenn das Mitglied oder die Funktion gelöscht wird. (Cascade)
    """
    mitglied = models.ForeignKey(Mitglied, on_delete=models.CASCADE, null=False)
    funktion = models.ForeignKey(Funktion, on_delete=models.CASCADE, null=False)
    amtszeit_beginn = models.DateField(null=True)
    amtszeit_ende = models.DateField(null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.mitglied.__str__() + ", " + self.funktion.__str__()
    class Meta:
        verbose_name = "Zuordnung Mitglied-Amt"
        verbose_name_plural = "Zuordnungen Mitglied-Amt"

class MitgliedMail(models.Model):
    """
    Datenbankmodell Zuordnung Mitglied-Mail

    Felder:

    * mitglied: Referenziert ein Mitglied. Darf nicht null sein.
    * email: Eine E-Mail-Adresse des Mitglieds. Darf nicht null sein.
    * history

    Es ist zu beachten, dass diese Zuordnung gelöscht wird, wenn das Mitglied gelöscht wird. (Cascade)
    """
    mitglied = models.ForeignKey(Mitglied, on_delete=models.CASCADE, null=False)
    email = models.CharField(max_length=50, null=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.email + " " + self.mitglied.__str__()
    class Meta:
        verbose_name = "Zuordnung Mitglied-Mail"
        verbose_name_plural = "Zuordnungen Mitglied-Mail"

src/aemter/views.py
from datetime import date
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Organisationseinheit, Unterbereich, Funktion
from mitglieder.models import MitgliedAmt

# Create your views here.
def main_screen(request):
    """
       Zeigt den Funktionen-Tab an
    """
    if not request.user.is_authenticated:
        messages.error(request, "Du musst angemeldet sein, um diese Seite sehen zu können.")
        return redirect("/")

    organisationseinheiten = Organisationseinheit\
        .objects.all()\
        .order_by('bezeichnung')
    paginator = Paginator(organisationseinheiten, 15) # Show 15 entries per page
    page_number = request.GET.get('page') # Get page number from request
    organisationseinheit_page = paginator.get_page(page_number) # Get entries for that page
    organisationseinheiten_ids = organisationseinheit_page.object_list.values_list('id', flat=True) # Get IDs of those entries

    # Only get associated data for current page
    unterbereiche = Unterbereich.objects.filter(organisationseinheit__id__in=organisationseinheiten_ids)
    funktionen = Funktion.objects.filter(Q(organisationseinheit__id__in=organisationseinheiten_ids) | Q(unterbereich__id__in=unterbereiche))
    funktionen_ids = funktionen.values_list('id', flat=True)

    # get current mitglieder funktionen
    mitglieder = MitgliedAmt.objects\
        .filter(Q(funktion__id__in=funktionen_ids) & Q(Q(amtszeit_ende__isnull=True) | Q(amtszeit_ende__gte=date.today())))

    # get prev mitglieder funktionen
    prev_mitglieder = MitgliedAmt.objects\
        .raw('SELECT * From (SELECT funktion_id, MAX(amtszeit_ende) as max_time FROM mitglieder_mitgliedamt GROUP BY funktion_id) u INNER JOIN mitglieder_mitgliedamt m ON m.funktion_id = u.funktion_id AND  m.amtszeit_ende = u.max_time')
        #.filter(amtszeit_ende__lt=date.today())

    context = {
        'referate': organisationseinheit_page,
        'unterbereiche': unterbereiche,
        'aemter': funktionen,
        'mitglieder': mitglieder,
        # type: MitgliedAmt
        'prev_mitglieder': prev_mitglieder
    }

    return render(request, 'aemter/main_screen.html', context)

src/mitglieder/templates/mitglieder/bereich_dropdown_list_options.html
<div class="input-field col s10 m8 l4">
    <select id="selectbereich{{amtid}}" data-url="{% url 'mitglieder:aemter_laden' %}" name="selectbereich{{amtid}}" class="selectbereich">
        <option selected="selected" disabled selected>Bereich auswählen</option>
        <!-- Zu Mitglied wurde bereits ein Unterbereich gespeichert-->
        {% if funktion %}
            {% if funktion.organisationseinheit.funktionen_ohne_unterbereich_count > 0 %}
                <option type="hidden" {% if not funktion.unterbereich %}selected="selected"{% endif %} value="-1">Keiner</option>
            {% endif %}
            {% for bereich in funktion.organisationseinheit.unterbereich_set.all %}
                <option {% if bereich.id == funktion.unterbereich.id %}selected="selected"{% endif %} value="{{bereich.id}}">{{bereich.bezeichnung}}</option>
            {% endfor %}
        <!-- Neue Organisationseinheit wurde ausgewaehlt -->
        {% else %}
            {% if funktionen_ohne_unterbereich_count > 0 %}
                <option type="hidden" value="-1">Keiner</option>
            {% endif %}
            {% for bereich in bereiche %}
                <option value="{{bereich.id}}">{{bereich.bezeichnung}}</option>
            {% endfor %}
        {% endif %}
    </select>
    <label>Bereich</label>
</div>

src/mitglieder/templates/mitglieder/email_input.html
<div id="div_email{{id}}" class="row">
    <div class="col s10 m8 l6">
      <div class="input-field">
        <input id="email{{id}}" type="email" name="email{{id}}" type="text" class="validate" {% if email %}value="{{email.email}}"{% endif %}>
        <label id="emaillabel{{id}}" for="email{{id}}">E-Mail</label>
      </div>
    </div>
    <div class="col s2 m2 l1" style="padding-top: 16px">
      <a id="emaildelbtn{{id}}" data-url="{% url 'mitglieder:email_loeschen' %}" class="emaildelbtn waves-effect waves-light btn-floating amber"><i class="material-icons black-text">delete</i>Entfernen</a>
    </div>
  </div>

src/mitglieder/templates/mitglieder/mitglieder.html
{% extends 'base.html' %}

{% block content %}
    <!-- Top Menu -->
    <div>
        <div class="row">
          <div class="col s12">
            <h3>Mitglieder</h3>
          </div>
          <div class="col s12">
              <!-- Serch Entry -->
              <div class="input-field inline" style="margin-top: 27px">
                  <input data-url="{% url 'mitglieder:suchen' %}" class="validate" type="text" id="search">
                  <label for="search">Suchen...</label>
              </div>

              <!-- Search Button -->
              <a id="searchbtn" class="btn-floating waves-effect waves-light amber">
                <i class="material-icons black-text">search</i>
              </a>
              {% if request.user.is_superuser %}
              <div class="right hide-on-med-and-down" style="margin-top: 29px">
                <a href="/mitglieder/erstellen" class="waves-effect waves-light btn amber black-text"><i class="material-icons left">add</i>Hinzufügen</a>
                <a id="delbtnl" class="delmitglieder disabled waves-effect waves-light btn amber black-text"><i class="material-icons left">delete</i>Entfernen</a>
              </div>
              <div class="right hide-on-large-only" style="margin-top: 29px">
                <a href="/mitglieder/erstellen" class="btn-floating waves-effect waves-light amber"><i class="material-icons black-text">add</i></a>
                <a id="delbtns" class="delmitglieder disabled btn-floating waves-effect waves-light amber"><i class="material-icons black-text">delete</i></a>
              </div>
              {% endif %}
          </div>
        </div>
    </div>

    <div id="notification" class="row"></div>

    <!-- Erstellen der Mitgliederliste -->
    <div>
      <div class="row" id="tbody">
        {% include 'mitglieder/row.html' %}
      </div>
    </div>

    <!-- Modal fuer Mitglied -->
    <div id="modal" class="modal"></div>

    <!-- Modal fuer Loeschbestaetigung von Mitglied(ern) -->
    <div id="modal-delete" class="modal">
      <div class="modal-content">
        <h4>Mitglieder löschen</h4>
        <p id="bestaetigungsfrage">Sollen folgende Mitglieder wirklich endgültig gelöscht werden?</p>
        <ul id="mitglieder-modal-delete">
        </ul>
      </div>
      <div class="modal-footer">
        <a id="delmitgliederconfirm" data-url="{% url 'mitglieder:mitglieder_loeschen' %}" href="#!" class="left modal-action modal-close waves-effect waves-green btn-flat ">Ja</a>
        <a href="#!" class="left modal-action modal-close waves-effect waves-red btn-flat ">Nein</a>
     </div>
    </div>
  

    <style>
        tr:hover {
            cursor:pointer;
        }
    </style>

    <script>
      var selectedcheckboxes_num = 0;
      var page = 0;

      $(document).ready(function(){
        // Initalisieren des Modals
        var elems = document.querySelectorAll('.modal');
        var instance = M.Modal.init(elems, {dismissible: true});

        addCheckboxEventListeners();
        addRowEventListeners();

        // Mitgliedersuche ueber Button
        $("#searchbtn").click(function(event){
          page = 1;
          search();
        });

        // Neue Suche bei Seitenwechsel triggern
        $(".page-link").on("click", function(event){
          page = $(event.target).attr('data-page');
          search();
        });


        // Mitgliedersuche ueber Enter-Taste
        $("#search").keyup("enterKey", function(e){
          if (e.keyCode == 13) {
            page = 1;
            search();
          } 
        });
        
        function search(){
          search_string = $("#search").val();
          var url = $("#search").attr('data-url');

          $.ajax({
            type: 'GET',
            url: url,
            data: {
              search_string: search_string,
              page: page
            },
            success: function(data){
              // Speichern der Ids von ueber Checkboxen ausgewaehlten Mitgliedern
              mitgliederids=[];
              $('input[type=checkbox]').each(function () {
                if (this.checked){
                  var mitgliedid = this.id.substr(4);
                  mitgliederids.push(mitgliedid); 
                }
              });
              // Aktualisierung der Mitgliedertabelle auf Basis der Suche
              $("#tbody").html(data);
              // Hinzufuegen von Event Listenern zum Oeffnen des Modals und Auswaehlen von Mitgliedern
              addRowEventListeners();
              addCheckboxEventListeners();
              // Auswaehlen aller Mitglieder, die vor Suche ausgewaehlt waren und angezeigt werden
              selectedcheckboxes_num = 0;
              for (mitgliedid of mitgliederids){
                if($("#chk-" + mitgliedid).length) selectedcheckboxes_num++;
                $("#chk-" + mitgliedid).prop('checked', true);
              }

              // Re-add event Listener
              $(".page-link").on("click", function(event){
                page = $(event.target).attr('data-page');
                search();
              });
            }
          });
        }

        // Anklicken eines Eintrags fuehrt zum Oeffnen des Modals
        function addRowEventListeners(){
          $('[class^="mitglied-"]').click(function(event){
          event = event.target;
          do {
            event = event.parentNode;
          } while (event.tagName!="TR");
          mitgliedid = event.id.substr(2);
          url = event.getAttribute('data-url');

          $.ajax({
            type: 'GET',
            url: url,
            data: {
              mitgliedid: JSON.stringify(mitgliedid),
              csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function(data){
              var modal = $("#modal");
              modal.html(data);

              //Modal oeffnen 
              var instance = M.Modal.getInstance(modal)
              instance.open();
            }
          });
        })
        }

        // Speichern der Anzahl der selektierten Checkboxen, um den Loeschbutton bei 0 Selektionieren zu deaktivieren
        function addCheckboxEventListeners(){
        $('input[type=checkbox').click(function(){
          if (this.checked){
            selectedcheckboxes_num++;
            if (selectedcheckboxes_num==1){
              $("#delbtnl").removeClass("disabled");
              $("#delbtns").removeClass("disabled");
            }
          } else{
            selectedcheckboxes_num--;
            if (selectedcheckboxes_num==0){
              $("#delbtnl").addClass("disabled");
              $("#delbtns").addClass("disabled");
            }
          }
        });
        }

        // Bestaetigung, dass Mitglieder geloescht werden sollen ueber Oeffnen eines Modals
        $('.delmitglieder').click(function(event){
          var modal = $("#modal-delete");
          var instance = M.Modal.getInstance(modal)
          $("#mitglieder-modal-delete").html("");
          $('input[type=checkbox]').each(function() {
            if (this.checked){
              var mitgliedid = this.id.substr(4);
              var mitgliedname = $("#mitgliedname-"+mitgliedid).text();
              $("#mitglieder-modal-delete").append("<li>" + mitgliedname + "</li>")
            }
          });
          if (selectedcheckboxes_num==1){
            $("#bestaetigungsfrage").html("Sollen folgendes Mitglied wirklich endgültig gelöscht werden?");
          } else{
            $("#bestaetigungsfrage").html("Sollen folgende Mitglieder wirklich endgültig gelöscht werden?");
          }
          instance.open();
        });

        // Mitglied(er) loeschen
        $('#delmitgliederconfirm').click(function(){
          var url = $("#"+this.id).attr('data-url');
          var mitgliederids = [];
          $('input[type=checkbox]').each(function () {
            if (this.checked){
              this.checked = false;
              var mitgliedid = this.id.substr(4);
              $("#tr" + mitgliedid).remove();
              mitgliederids.push(mitgliedid); 
            }
          });
          
          $.ajax({
            type: 'POST',
            url: url,
            data: {
              mitglieder:JSON.stringify(mitgliederids),
              csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function(data){
              // Meldung, dass Mitglieder erfolgreich geloescht wurden
              $("#notification").html("Mitglieder wurden erfolgreich gelöscht");
              selectedcheckboxes_num=0;
              // Deaktivieren des Loeschbuttonss
              $("#delbtnl").addClass("disabled");
              $("#delbtns").addClass("disabled");
            }
          });
        });
      });
    </script>
{% endblock %}

src/mitglieder/templates/mitglieder/row.html
{% load mitglieder_extras %}
<div class="col s12">
    <table class="highlight">
        <thead>
            <tr>
            <th></th>
            <th></th>
            <th>Name</th>
            <th>Funktionen</th>
            <th class="hide-on-small-only">E-Mails</th>
            {% if request.user.is_superuser %}
            <th class="hide-on-med-and-down">Telefon</th>
            {% endif %}
            <th></th><th></th>
            </tr>
        </thead>

        <tbody>
            {% for entry in data %}
                <!-- Zeile -->
                <tr id="tr{{entry.id}}" class="mitglied" data-url="{% url 'mitglieder:mitglied_laden' %}" >
                    <td>                  
                    {% if request.user.is_superuser %}
                        <!-- Checkbox -->
                        <form method="post" style="margin-bottom: 0px; margin-top: 4px; padding-left: 7px; padding-right: 7px;">
                            {% csrf_token %}
                            <label for="chk-{{entry.id}}">
                                <input type="checkbox" class="filled-in checkbox-amber" id="chk-{{entry.id}}"/>
                                <span style="padding-left: 7px; padding-right: 7px;"></span>
                            </label>
                        </form>
                        {% endif %}
                    </td>
                    <td>
                        {% if request.user.is_superuser %}
                            <!-- Attention symbol-->
                            {% if not entry.admission_data_complete %}
                                <i class="material-icons red-text">priority_high</i>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td id="mitgliedname-{{entry.id}}" class="mitglied-{{entry.id}}">{{entry.vorname}} {{entry.name}}</td>
                    <td class="mitglied-{{entry.id}}">
                        {% if entry.curr_funktion_first %}
                        <ul style="margin-bottom: 0px">
                            <li>{{entry.curr_funktion_first}}</li>
                            {% if entry.curr_funktion_count > 1 %}
                                <li>...</li>
                            {% endif %}
                        </ul>
                        {% else %}-
                        {% endif %}
                    </td>
                    <td class="mitglied-{{entry.id}} hide-on-small-only">
                        {% if entry.mitgliedmail_set.all %}
                        <ul style="margin-bottom: 0px">
                            <li>{{entry.mitgliedmail_set.first.email}}</li>
                            {% if entry.mitgliedmail_set.all.count > 1 %}
                                <li>...</li>
                            {% endif %}
                        </ul>
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    {% if request.user.is_superuser %}
                    <td class="mitglied-{{entry.id}} hide-on-med-and-down">
                        {{entry.tel_mobil|default:'-'}}
                    </td>
                    {% endif %}
                    
                    <td>
                        {% if entry.mitgliedmail_set.all %}
                        <!-- email button -->
                        <a href="mailto:{{entry.mitgliedmail_set.first.email}}"><i class="material-icons black-text">email</i></a>
                        {% endif %}
                    </td>
                    
                    {% if request.user.is_superuser %}
                    <!-- edit button (pencil) -->
                    <td>
                        <a href="{% url 'mitglieder:bearbeitenView' entry.id %}"><i class="material-icons black-text">create</i></a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Pagination -->
<div class="col s12 center-align">
    <ul class="pagination">
    {% if data.has_previous %}
        <li class="waves-effect"><a class="page-link" data-page="1">1</a></li>
        {% if data.number > 3 %}
        <li class="waves-effect"><a class="page-link" data-page="{{ data.previous_page_number|add:-1 }}">{{ data.previous_page_number|add:-1 }}</a></li>
        {% endif %}
        {% if data.number != 2 %}
        <li class="waves-effect"><a class="page-link" data-page="{{ data.previous_page_number }}">{{ data.previous_page_number }}</a></li>
        {% endif %}
    {% endif %}
    <li class="active" style="background-color: #ffc107"><a class="page-link">{{ data.number }}</a></li>
    {% if data.has_next %}
        {% if data.number != data.paginator.num_pages|add:-1 %}
        <li class="waves-effect"><a class="page-link" data-page="{{ data.next_page_number }}">{{ data.next_page_number }}</a></li>
        {% endif %}
        {% if data.number < data.paginator.num_pages|add:-2 %}
        <li class="waves-effect"><a class="page-link" data-page="{{ data.next_page_number|add:1 }}">{{ data.next_page_number|add:1 }}</a></li>
        {% endif %}
        <li class="waves-effect"><a class="page-link" data-page="{{ data.paginator.num_pages }}">{{ data.paginator.num_pages }}</a></li>
    {% endif %}
    </ul>
</div>